### ISSUE TITLE
Tool not started as you said in the readme

### ISSUE THREAD

**Issue by gowtham758550** [Anish-M-code/Simple_Website_blocker#3]
![Screenshot from 2022-01-22 18-28-02](https://user-images.githubusercontent.com/63159252/150639604-7ef18d74-9043-4987-a3ea-ef808ec145f7.png)

@Anish-M-code

**Comment by Anish-M-code** [comment]
Hi , it seems in kali linux and in certain Debian based linux distributions you may have to add a specific location given via a warning during installation to PATH environment variable via .bashrc or .zshrc ( in kali linux)

just add : -

export PATH = "some location indicated via warning":$PATH

**Comment by Anish-M-code** [comment]
Incase if your still facing issues or the above steps look too complex then please use for debian based linux distros : -

python3 -m websiteblocker
